siteTitle = "Christian Fuchs"
siteDescr = "Dies wird mal eine Website für Christian."
siteAuthor = ""

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

linkPrefix = ""
