siteTitle = "fuchs+wald"
siteDescr = "digitaldialoge – Email Marketing, Templateprogrammierung, Projektmanagement, Seminare & Workshops."
siteAuthor = ""

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

linkPrefix = ""
